In [2]:
import pandas as pd

In [3]:
# 점수입력
data = {
    '3P' : [3.4],
    'BLK' : [0.5],
    'TRB' : [3.7]
}
df = pd.DataFrame(data)
df

    3P  BLK  TRB
0  3.4  0.5  3.7

In [4]:
import joblib

In [5]:
knn = joblib.load("../Data/knn_basketball.h5")

pred = knn.predict(df)
print(f"추천하는 포지션은 {pred[0]} 입니다.")

추천하는 포지션은 SG 입니다.

----
iris.csv를 학습하여 모델을 저장한다.
- svm(svm_iris.h5)
- randomForest(rf_iris.h5)
- knn(knn_iris.h5)

저장된 모델을 불러서 예측하기    
- SepalLength : 5.1
- SepalWidth : 3.0
- PetalLength : 1.3
- PetalWidth : 0.2

In [38]:
# iris 데이터 불러오기
iris = pd.read_csv("../Data/iris.csv")
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [39]:
# data만들기
iris_data = iris[['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]
iris_data.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [40]:
# target 지정
iris_target = iris['Name']
iris_target.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [41]:
# train, test 데이터 분리
train_data, test_data, train_target, test_target = \
    train_test_split(
        iris_data,
        iris_target,
        random_state=42,
        stratify=iris_target
    )

In [15]:
print(train_data.shape)
print(train_target.shape)
print(test_data.shape)
print(test_target.shape)

(112, 4)
(112,)
(38, 4)
(38,)

#### SVM

In [12]:
# SVM
from sklearn.svm import SVC

In [13]:
clf_svm = SVC()

In [16]:
clf_svm.fit(train_data, train_target)

SVC()

In [17]:
# 검증하기
print("Train : ", clf_svm.score(train_data, train_target))
print("Test  : ", clf_svm.score(test_data, test_target))

Train :  0.9732142857142857
Test  :  0.9210526315789473

In [18]:
# 저장하기
joblib.dump(clf_svm, "../Data/svm_iris.h5")

['../Data/svm_iris.h5']

In [19]:
# 자료입력
svm_data = {
    'SepalLength' : [5.1],
    'SepalWidth' : [3.0],
    'PetalLength' : [1.3],
    'PetalWidth' : [0.2]
}
svm_df = pd.DataFrame(svm_data)
svm_df

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.0          1.3         0.2

In [ ]:
svm = joblib.load("../Data/svm_iris.h5")

svm_pred = svm.predict(svm_df)
print(f"예측값은 {svm_pred[0]} 입니다.")

예측값 Iris-setosa 입니다.

#### RandomForest

In [23]:
#randomforest
from sklearn.ensemble import RandomForestClassifier

In [24]:
clf_rf = RandomForestClassifier()

In [25]:
clf_rf.fit(train_data, train_target)

RandomForestClassifier()

In [27]:
# 검증하기
print("Train : ", clf_rf.score(train_data, train_target))
print("Test  : ", clf_rf.score(test_data, test_target))

Train :  1.0
Test  :  0.9473684210526315

In [28]:
joblib.dump(clf_rf, "../Data/rf_iris.h5")

['../Data/rf_iris.h5']

In [29]:
# 자료입력
rf_data = {
    'SepalLength' : [5.1],
    'SepalWidth' : [3.0],
    'PetalLength' : [1.3],
    'PetalWidth' : [0.2]
}
rf_df = pd.DataFrame(rf_data)
rf_df

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.0          1.3         0.2

In [30]:
rf = joblib.load("../Data/rf_iris.h5")

rf_pred = rf.predict(rf_df)
print(f"예측값은 {rf_pred[0]} 입니다.")

예측값은 Iris-setosa 입니다.

#### KNN

In [31]:
# knn
from sklearn.neighbors import KNeighborsClassifier

In [32]:
knn = KNeighborsClassifier(n_neighbors=5)

In [33]:
knn.fit(train_data, train_target)

KNeighborsClassifier()

In [34]:
print(knn.score(train_data, train_target))
print(knn.score(test_data, test_target))

0.9732142857142857
0.9736842105263158

In [35]:
joblib.dump(knn, "../Data/knn_iris.h5")

['../Data/knn_iris.h5']

In [36]:
# 자료입력
knn_data = {
    'SepalLength' : [5.1],
    'SepalWidth' : [3.0],
    'PetalLength' : [1.3],
    'PetalWidth' : [0.2]
}
knn_df = pd.DataFrame(knn_data)
knn_df

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.0          1.3         0.2

In [37]:
knn = joblib.load("../Data/knn_iris.h5")

knn_pred = knn.predict(rf_df)
print(f"예측값은 {knn_pred[0]} 입니다.")

예측값은 Iris-setosa 입니다.