# Dataframe 로딩, 기본 API

In [41]:
# 경고 메시지 무시
import warnings
warnings.filterwarnings(action='ignore') 

import pandas as pd
import numpy as np

# 1. 기본 API

### (1) read_csv()
- .csv 파일을 읽어오기

In [6]:
titanic_df = pd.read_csv("data/titanic/train.csv")
print(f"titanic_df type : {type(titanic_df)}")

titanic_df type : <class 'pandas.core.frame.DataFrame'>

### (2) display()
- 데이터프레임 형식을 출력

In [8]:
display(titanic_df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### (3) head(), tail()
- head() : 데이터프레임 앞쪽의 일부 데이터 추출(기본 5행), 데이터프레임.head(갯수)
- tail() : 데이터프레임 뒤쪽의 일부 데이터 추출(기본 5행), 데이터프레임.tail(갯수)

In [10]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [12]:
titanic_df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### (4) 여러 함수 실행 시 display 함수로 묶어줌

In [14]:
display(titanic_df.head(3))
display(titanic_df.tail(3))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### (5) shape
- 넘파이의 shape과 동일
- 데이터프레임의 행과 열 형태를 확인할 수 있음

In [15]:
titanic_df.shape

(891, 12)

In [16]:
titanic_df.ndim

2

# 2. Dataframe 생성

### (1) 리스트(list)로 생성

In [20]:
## 파이썬의 2차원 리스트 생성생성
list1 = [['김철수', 28, '개발자'], ['이영희', 34, '디자이너']]

# 리스트를 데이터프레임으로 생성
list_df = pd.DataFrame(list1, columns=['이름', '나이','직업'])
list_df

    이름  나이    직업
0  김철수  28   개발자
1  이영희  34  디자이너

### (2) 딕셔너리(dict)로 생성

In [31]:
# 파이썬의 딕셔너리를 이용하여 데이터프레임 생성
dic1 = {'Name': ['이순신', '유관순','김유신','홍길동'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }
dic1

{'Name': ['이순신', '유관순', '김유신', '홍길동'],
 'Year': [2011, 2016, 2015, 2015],
 'Gender': ['Male', 'Female', 'Male', 'Male']}

In [32]:
# 딕셔너리로 데이터프레임 생성
dict_df = pd.DataFrame(dic1)
dict_df

  Name  Year  Gender
0  이순신  2011    Male
1  유관순  2016  Female
2  김유신  2015    Male
3  홍길동  2015    Male

In [39]:
# dict_df 데이터프레임에 컬럼명 추가, 인덱스 변경
dict_df2 = pd.DataFrame(dic1, 
                        columns=['Name','Year','Gender','Age','Address'],
                        index=['a','b','c','d'])
dict_df2

  Name  Year  Gender  Age Address
a  이순신  2011    Male  NaN     NaN
b  유관순  2016  Female  NaN     NaN
c  김유신  2015    Male  NaN     NaN
d  홍길동  2015    Male  NaN     NaN

### (3) ndarray로 생성

In [43]:
array1 = np.array([['김철수', 30, '개발자'], ['이영희', 20, '디자이너']])
array1

array([['김철수', '30', '개발자'],
       ['이영희', '20', '디자이너']], dtype='<U21')

In [47]:
array_df = pd.DataFrame(array1, columns=['Name', 'Age', 'Job'], index=['one','two'])
array_df

    Name Age   Job
one  김철수  30   개발자
two  이영희  20  디자이너

### (4) 파일로 생성 - read_csv()...

In [53]:
titanic_df = pd.read_csv("data/titanic/train.csv")
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 3. DataFrame의 컬럼명과 인덱스

In [ ]:
# 컬럼리스트, 인덱스 범위, 인덱스 값 출력
print(f"컬럼리스트 : {titanic_df.columns}")
print(f"인덱스 범우; : {titanic_df.index}")
print(f"인덱스 값 : {titanic_df.index.values}")

# 4. info() 
- 데이터프레임의 컬럼명, 데이터 타입, NaN(Null) 건수, 데이터 건수 등의 정보를 출력

In [56]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# 5. describe()
- count 계산시 널 값 제외한 수치, Survived(생존유/무), Pclass(선실등급) 등은 카테고리성 데이터 이지만 수치형 데이터는 모두 출력됨을 확인 데이터값들의 평균,표준편차,4분위 분포도를 제공합니다. 숫자형 컬럼들에 대해서 해당 정보를 제공합니다.

In [58]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 6. value_counts()
- 동일한 개별 데이터 값이 몇건이 있는지 정보를 제공

In [63]:
tt_value_counts = titanic_df['Survived'].value_counts()
print(tt_value_counts, type(tt_value_counts))

Survived
0    549
1    342
Name: count, dtype: int64 <class 'pandas.core.series.Series'>

In [64]:
# 두 개 이상의 컬럼을 출력하는 경우, 2차원 형태로 입력
tt_value_counts = titanic_df[['Survived', 'Pclass']].value_counts()
print(tt_value_counts, type(tt_value_counts))

Survived  Pclass
0         3         372
1         1         136
          3         119
0         2          97
1         2          87
0         1          80
Name: count, dtype: int64 <class 'pandas.core.series.Series'>