# DataFrame과 리스트, 딕셔너리, ndarray 상호 변환

### 1. 1차원 데이터를 DataFrame 으로 변환

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [4]:
# 1차원 리스트 생성
col_name1 = ['col_1']
list1 = [1, 2, 3]
print(type(list1,), list1)

<class 'list'> [1, 2, 3]

In [5]:
# ndarray로 변환
array1 = np.array(list1)
print(type(array1), array1)

<class 'numpy.ndarray'> [1 2 3]

In [12]:
# list1, array1를 DataFrame으로 생성(변환)
df1_1 = pd.DataFrame(list1, columns = col_name1, index = ['a','b','c'])
df1_2 = pd.DataFrame(array1, columns = col_name1)
print(df1_1)
print('-'*30)
print(df1_2)

   col_1
a      1
b      2
c      3
------------------------------
   col_1
0      1
1      2
2      3

### 2. 2차원 데이터를 DataFrame 으로 변환

In [13]:
# 컬럼명 생성
col_names = ['col1','col2','col3']
col_names

['col1', 'col2', 'col3']

In [14]:
# 2차원 리스트 생성
list2 = [[1, 2, 3],
        [4, 5, 6]]
list2

[[1, 2, 3], [4, 5, 6]]

In [15]:
# list2를 ndarray로 변환
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# list2, array2를 DataFrame으로 변환
df2_1 = pd.DataFrame(list2, columns = col_names)
df2_2 = pd.DataFrame(array2, columns = col_names)
print(df2_1, type(df2_1))
print('-'*30)
print(df2_2, type(df2_2))

   col1  col2  col3
0     1     2     3
1     4     5     6 <class 'pandas.core.frame.DataFrame'>
------------------------------
   col1  col2  col3
0     1     2     3
1     4     5     6 <class 'pandas.core.frame.DataFrame'>

## 3. 딕셔너리를 DataFrame으로 변환

In [19]:
# 딕셔너리 생성
dict1 = {
    'col1' : [1, 2, 3],
    'col2' : [4, 2, 3],
    'col3' : [5, 2, 3]
}
dict1

{'col1': [1, 2, 3], 'col2': [4, 2, 3], 'col3': [5, 2, 3]}

In [20]:
# DataFrame 생성
df_dict1 = pd.DataFrame(dict1)
df_dict1

   col1  col2  col3
0     1     4     5
1     2     2     2
2     3     3     3

## 4. DataFrame을 ndarray, list, dictionary로 전환

In [23]:
# df_dict1 데이터프레임을 ndarray로 변환
array3 = df_dict1.values
print(type(array3), '\n', array3)

<class 'numpy.ndarray'>
 [[1 4 5]
 [2 2 2]
 [3 3 3]]

In [25]:
# df_dict1 데이터프레임을 list로 변환, DataFrame.values > Numpy.tolist() > list
list3 = df_dict1.values.tolist()
print(type(list3), '\n', list3)

<class 'list'>
 [[1, 4, 5], [2, 2, 2], [3, 3, 3]]

In [26]:
# df_dict1 데이터프레임을 dictionary로 변환
dict3 = df_dict1.to_dict()
print(type(dict3), '\n', dict3)

<class 'dict'>
 {'col1': {0: 1, 1: 2, 2: 3}, 'col2': {0: 4, 1: 2, 2: 3}, 'col3': {0: 5, 1: 2, 2: 3}}

## 5. shape 속성 정리
- python List : ❌ AttributeError
- python Dictionary : ❌ AttributeError
- Numpy ndarray : 사용 가능
- Pandas DataFrame : 사용 가능
- Pandas Series : 사용 가능

In [ ]:
# list 생성
print(type(list1), list1)
print(f"shpae : {list1.shape}") # ❌ AttributeError: 'list' object has no attribute 'shape'

In [ ]:
# dictionary 생성
print(type(dict1), dict1)
print(f"shpae : {dict1.shape}") # ❌ AttributeError: 'dict' object has no attribute 'shape'

In [32]:
# array
print(type(array1), array1)
print(f"shpae : {array1.shape}")

<class 'numpy.ndarray'> [1 2 3]
shpae : (3,)

In [33]:
# DataFrame
# array
print(type(df_dict1), df_dict1)
print(f"shpae : {df_dict1.shape}")

<class 'pandas.core.frame.DataFrame'>    col1  col2  col3
0     1     4     5
1     2     2     2
2     3     3     3
shpae : (3, 3)

## 6. DataFrame 컬럼 데이터 생성 및 수정

#### 타이타닉(Titanic) 데이터 셋 로드

In [ ]:
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df

In [ ]:
# 상위 5개의 데이터셋 조회
titanic_df.head()

In [ ]:
# 하위 5개의 데이터셋 조회
titanic_df.tail()

In [38]:
# 하위 5개의 데이터셋 조회
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [39]:
# 데이터셋 수치 정보 조회
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [45]:
# Age_0 컬럼 추가
titanic_df.info()
titanic_df['Age_0'] = 1 # 컬럼 존재 : 값 업데이트, 컬럼 ❌ : 생성 
titanic_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [47]:
# Age_by_10 컬럼 추가, Age * 10 값 저장
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df.info()
titanic_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
 13  Age_by_10    714 non-null    float64
dtypes: float64(3), int64(6), object(5)
memory usage: 97.6+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,350.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,350.0

In [52]:
# 일부 컬럼 조회
titanic_df['Age'] # 단일 컬럼 조회시 1차원 Series 반환
titanic_df[['Age', 'Age_0', 'Age_by_10']].head() # 다중 컬럼 조회 시 2차원 형태

    Age  Age_0  Age_by_10
0  22.0      0      220.0
1  38.0      0      380.0
2  26.0      0      260.0
3  35.0      0      350.0
4  35.0      0      350.0

In [54]:
# Family_no 컬럼 추가, Sibsp 컬럼 + Parch 컬럼 값 합계 + 1
titanic_df.info()
titanic_df['Family_no'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
 13  Age_by_10    714 non-null    float64
dtypes: float64(3), int64(6), object(5)
memory usage: 97.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
 13  Age_by_10    714 non-null    float64
 14  Family_no    891 non-null    int64
dtypes: float64(3), int64(7), object(5)
memory usage: 104.5+ KB

In [55]:
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_no
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S,0,270.0,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S,0,190.0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S,0,NaN,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C,0,260.0,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q,0,320.0,1

## 7. DataFrame 데이터 삭제
- drop(컬럼리스트, axis)

In [56]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
 13  Age_by_10    714 non-null    float64
 14  Family_no    891 non-null    int64
dtypes: float64(3), int64(7), object(5)
memory usage: 104.5+ KB

In [62]:
# Age_0 컬럼 삭제
td_drop = titanic_df.drop('Age_0', axis=1) #axis=0 행 기준 실행시 에러 발생, axis=1 실행, 삭제 실행 후 새로운 객체 반환

In [ ]:
titanic_df.head() # Age_0 객체 O
td_drop.head()    # Age_0 객체 X

In [68]:
# 원본 데이터셋(titanic_df)의 Age_0 컬럼 삭제 후 반영
titanic_df.drop('Age_0', axis=1, inplace=True)

In [69]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_by_10    714 non-null    float64
 13  Family_no    891 non-null    int64
dtypes: float64(3), int64(6), object(5)
memory usage: 97.6+ KB

In [70]:
# 다중 컬럼 삭제 - Age_by_10, Family_no 컬럼 동시 삭제, 원본에 반영
titanic_df.drop(['Age_by_10', 'Family_no'], axis=1, inplace=True)

In [71]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
titanic_df.head()
titanic_df.drop(0) # index행, axis=0 행기준, inplace=False 새로운 객체 반환

In [ ]:
# 0, 1, 2, 인덱스 삭제, 원본에 반영
titanic_df.drop([0, 1, 2], axis=0, inplace=True)
titanic_df.head(3)