# DataFrame Index

## Index란?
- Pandas의 Index는 데이터프레임과 시리즈의 각 행(row)를 고유하게 식별하는 역할을 수행함
- 관계형 데이터베이스의 Primary key(pk)와 유사한 개념
- 특징
  - 데이터 식별 역할 수행
  - 숫자, 문자열도 가능
  - 생성 후 직접 수정 불가
  - reset_index() 함수를 이용하여 재생성 가능

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

## 1. Index 객체

In [2]:
# Titanic 데이터셋 로드
titanic_df = pd.read_csv('data/titanic/train.csv')

In [4]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [7]:
# Index 객체 추출
td_indexs = titanic_df.index
td_indexs

RangeIndex(start=0, stop=891, step=1)

In [8]:
type(td_indexs)

pandas.core.indexes.range.RangeIndex

In [9]:
td_indexs.shape

(891,)

In [ ]:
td_indexs.values

In [15]:
# Index 객체 정보
print(f"type : {type(td_indexs)}")
print(f"shpae : {td_indexs.values.shape}")
print(f"shpae : {td_indexs.shape}")

print(f"Index 슬라이싱 : {td_indexs[:5].values}")
print(f"Index 슬라이싱 : {td_indexs.values[:5]}")

print(f"특정 Index 조회 : {td_indexs[5]}")
print(f"size 조회 : {td_indexs.size}")
print(f"is_unique 조회 : {td_indexs.is_unique}")

type : <class 'pandas.core.indexes.range.RangeIndex'>
shpae : (891,)
shpae : (891,)
Index 슬라이싱 : [0 1 2 3 4]
Index 슬라이싱 : [0 1 2 3 4]
특정 Index 조회 : 5
size 조회 : 891
is_unique 조회 : True

In [ ]:
# 생성된 Index 객체는 수정 불가 TypeError("Index does not support mutable operations")
# Index는 수정이 안되는 불변 객체임
td_indexs[0] = 100

## 2. Index 기반 연산 방식
- 판다스는 인덱스 이름을 기준으로 데이터를 맞춘 후 연산함

### (1) Series 연산
- 동일한 인덱스를 가진 데이터끼리만 연산됨

#### 기본 Series 생성 및 연산

In [20]:
# Series 생성
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([10, 20, 30])
print(s1,'\n', s2)

0    10
1    20
2    30
dtype: int64
 0    10
1    20
2    30
dtype: int64

In [ ]:
# Series 사칙 연산 - 동일한 인덱스 기준으로 연산이 진행됨
print(s1 + s2)
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)

#### Index 지정

In [22]:
s1 = pd.Series([10, 20, 30],
                index=['a','b','c'])
s1 = pd.Series([10, 20, 30],
                index=['b','c','d'])
print(s1,'\n', s2)

b    10
c    20
d    30
dtype: int64
 0    10
1    20
2    30
dtype: int64

In [ ]:
# Series 사칙 연산
print(s1 + s2)
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)

### (2) DataFrame 연산

#### DataFrame 생성

In [29]:
df = pd.DataFrame(
    {
        'col1': [10, 20, 30],
        'col2': [10, 20, 30]
    },
    index=['a', 'b','c']
)
df

   col1  col2
a    10    10
b    20    20
c    30    30

### 3. reset_index()
- reset_index()실행 시 기존 Index는 첫 번째 컬럼으로 이동하고, 새로운 숫자의 Index가 생성됨

In [30]:
# 데이터셋 확인
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
# 인덱스 재생성, reset_index()
td_reset_df = titanic_df.reset_index(inplace=False)
td_reset_df.head()

In [ ]:
# td_reset_df 객체의 인덱스 재생성
td_reset_df2 = td_reset_df.reset_index(inplace=False)
td_reset_df2.head(3)

In [ ]:
# td_reset_df2 객체의 level_0 컬럼 삭제, 원본 반영
td_reset_df2.drop('level_0', axis=1, inplace=True)
td_reset_df2.head()

In [ ]:
# td_reset_df2 객체의 0, 1, 2 인덱스 삭제, 원본 반영
td_reset_df2.drop([0, 1, 2], axis=0, inplace=True)
td_reset_df2.head()

In [ ]:
# td_reset_df2 객체의 인덱스 재생성, 원본 반영
td_reset_df2.reset_index(inplace=True)
td_reset_df2.head()

In [ ]:
td_reset_df2.drop(['level_0', 'index'], axis=1, inplace=True)
td_reset_df2

## 4. rename() - 컬럼명 변경
- 문법

  DataFrame.rename(columns={'기존 컬럼명' : '신규 컬럼명'})

In [43]:
# Age_0 컬럼 추가, 값은 0
titanic_df['Age_0'] = 0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [44]:
# Age_0 컬럼의 데이터를 1로 수정
titanic_df['Age_0'] = 1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1

In [ ]:
# Age_0 컬럼명을 Age_1 으로 수정
titanic_df.rename(columns={'Age_0':'Age_1'})
# titanic_df.head(3)

In [49]:
# 인덱스 0, 2, 4=> 'a', 'b', 'c' 변경
td_rename = titanic_df.rename(index= {0: "a", 2: "b", 4: "c"})
td_rename.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
a,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
b,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
c,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [51]:
td_rename_index = td_rename.index
td_rename_index

Index(['a',   1, 'b',   3, 'c',   5,   6,   7,   8,   9,
       ...
       881, 882, 883, 884, 885, 886, 887, 888, 889, 890],
      dtype='object', length=891)